name: Docker builder
on:
  push:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  docker_build:
    name: Docker builder
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Docker build
        env:
          REPOSITORY: exodus/firebase
        run: docker build -t $REPOSITORY .
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - name: Docker push
        env:
          REPOSITORY: exodus/firebase
        run: docker push $REPOSITORY
